export const SORT_OPTIONS = [
  { value: "recent", label: "Plus récents" },
  { value: "price-asc", label: "Prix croissant" },
  { value: "price-desc", label: "Prix décroissant" },
  { value: "rating", label: "Mieux notés" },
];

export const CATEGORY_RULES = [
  {
    slug: "electronique",
    name: "Électronique",
    description: "Tech, smartphones, ordinateurs et accessoires.",
    keywords: [
      "tech",
      "technologie",
      "electronique",
      "électronique",
      "phone",
      "smartphone",
      "ordinateur",
      "computer",
      "laptop",
      "pc",
      "gaming",
      "accessoire",
      "informatique",
      "casque",
      "chargeur",
      "camera",
      "écran",
      "ecran",
    ],
  },
  {
    slug: "mode",
    name: "Mode & Luxe",
    description: "Vêtements, chaussures, sacs et accessoires.",
    keywords: [
      "mode",
      "fashion",
      "luxe",
      "vetement",
      "vêtement",
      "chaussure",
      "sac",
      "bijou",
      "montre",
      "textile",
      "habit",
      "robe",
      "shirt",
      "pantalon",
    ],
  },
  {
    slug: "maison",
    name: "Maison & Design",
    description: "Décoration, mobilier, cuisine et maison.",
    keywords: [
      "maison",
      "home",
      "design",
      "deco",
      "déco",
      "decoration",
      "décoration",
      "meuble",
      "mobilier",
      "cuisine",
      "jardin",
      "interieur",
      "intérieur",
    ],
  },
  {
    slug: "beaute",
    name: "Beauté & Bien-être",
    description: "Cosmétiques, soins, parfums et bien-être.",
    keywords: [
      "beaute",
      "beauté",
      "beauty",
      "cosmetique",
      "cosmétique",
      "soin",
      "parfum",
      "cheveux",
      "skin",
      "visage",
      "wellness",
      "bien etre",
      "bien-être",
    ],
  },
  {
    slug: "alimentation",
    name: "Alimentation",
    description: "Produits alimentaires, boissons et restauration.",
    keywords: [
      "food",
      "alimentaire",
      "alimentation",
      "restaurant",
      "cuisine",
      "epicerie",
      "épicerie",
      "boisson",
      "snack",
      "patisserie",
      "pâtisserie",
      "repas",
    ],
  },
  {
    slug: "artisanat",
    name: "Artisanat",
    description: "Créations locales, fait main et produits artisanaux.",
    keywords: [
      "artisan",
      "artisanat",
      "handmade",
      "fait main",
      "local",
      "creation",
      "création",
      "atelier",
      "traditionnel",
    ],
  },
  {
    slug: "autres",
    name: "Autres",
    description: "Autres produits disponibles sur Equator.",
    keywords: [],
  },
];

export const CATEGORY_PRODUCTS_PER_PAGE = 8;
